---
title: "Homework 5"
author: "Natalie Boychuk"
date: "11/15/2020"
output: github_document 
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(rvest)
library(purrr)
library(ggplot2)
library(patchwork)
set.seed(1)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1 
Read in the data 
```{r}
  homicide_df = 
    read_csv("data/homicide-data.csv") %>% 
    mutate(
      city_state = str_c(city, state, sep = "_"),
      resolved = case_when(
        disposition == "Closed without arrest" ~ "unsolved",
        disposition == "Open/No arrest" ~ "unsolved",
        disposition == "Closed by arrest" ~ "solved"
        )
    ) %>% select(city_state,resolved) %>% 
  filter(city_state != "Tulsa_AL")

```

```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  ) 
```

```{r}
prop.test(
  aggregate_df %>%  filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
   aggregate_df %>%  filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()

```

```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low,conf.high)
```

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

##Problem 2 

```{r eval = FALSE, echo = FALSE }
longstudy_df = 
  tibble(
  path = list.files("data/experiment-data")) %>% 
  mutate(
    path = str_c("data/experiment-data/", path),
    data = map(.x = path, ~read_csv(.x))) %>% 
      separate(path, c("file1","file2","name"), sep = "/") %>% 
      separate(name, c("arm","id","csv")) %>% 
         mutate(arm = recode(arm, con = "control", exp = "case")) %>% 
            select(-file1, -file2, -csv) %>% 
  unnest(data) %>% 
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "observation",
               names_prefix = "week_")

```

```{r eval = FALSE, echo = FALSE}
cases = 
  longstudy_df %>% 
  filter(arm == "case") %>% 
  mutate(as.numeric(week))

controls = 
  longstudy_df %>%
  filter(arm == "control") %>% 
  mutate(as.numeric(week))

case_plot = ggplot(data = cases, aes(x = week, y = observation, group = id)) + geom_line(aes(color = id)) + 
  labs(
    title = "Observations of Cases by Week",
    x = "Time (weeks)",
    y = "Observation"
  ) + 
  scale_color_hue(name = "Participant ID")

control_plot = ggplot(data = controls, aes(x = week, y = observation, group = id)) + geom_line(aes(color = id)) + 
  labs(
    title = "Observations of Controls by Week",
    x = "Time (weeks)",
    y = "Observation"
  ) + 
  scale_color_hue(name = "Participant ID")

control_plot + case_plot

```

## Problem 3 

```{r setting up function}

simfun = function(samp_size = 30, mu = 0, sigma = 5){
  
  prob3_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma)
    ) 
  
    prob3_ttest = 
     t.test(prob3_data, conf.level = .95) %>% 
      broom::tidy()
}

```

```{r}
mu_sim =
  tibble(
    mu = c(0, 1, 2, 3, 4, 5, 6)
  ) %>% 
  mutate(
    result = map(.x = mu, ~rerun(5000, simfun(mu = .x))),
    result_df = map(result, bind_rows)
  ) 
```

```{r}
unnest(mu_sim, cols = c("result_df"))

power_list = 
  mu_sim %>% 
mutate(decision = case_when(
  "p.value" < .05 ~ "reject",
  "p.value" > .05 ~ "fail.reject")) %>% 
  mutate(power_var = 
           (mean(decision == "reject"))
  ) 

```

```{r}
power_list %>% 
  ggplot(aes(x = mu, y = power_var)) +
  geom_point() + 
  labs(
    title = "Relationship Between Effect Size and True Mean (Mu)",
    x = "True Mean", 
    y = "Power"
  )
```

